app:
  datasource:
    jdbc-url: jdbc:postgresql://172.17.0.2:5432,localhost:5432/cryptodb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: postgres
    password: password
    pool-size: 30


  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout:
      seconds: 900
